import os
import fnmatch

Import('*')

env = env.Clone()
env["ENV"]["TEXMFHOME"] = os.environ["TEXMFHOME"]

env.Install("#", env.Latex("note.tex",TEXINPUTS=".:files:"))

def rGlob(pattern, dirname='.'):
    """
    Recursivly glob through directories, finding all files matching pattern

    FIXME: Does not work when source_dir contains build_dir, then it will find
    them in ./ and in build_dir/.
    TODO: Maybe use scons Glob to ensure same pattern syntax, not fnmatch.filter
    """
    dir = Dir(dirname)
    dirs = dir.Rfindalldirs('.')
    for srcdir in dirs:
        for dirname,dirs,files in os.walk( str(srcdir) ):
            basedir = os.path.join(str(dir),dirname[len(str(srcdir))+1:])
            for filename in fnmatch.filter(files,pattern):
                yield os.path.join(basedir,filename)

for file in rGlob('*.svg','files'):
    env.InkPDF(source=file)
