Import('*')

ddkEnv = env.Clone()
ddkSource = Glob("src/*.cc")
ddkLib = ddkEnv.SharedLibrary("ddk",ddkSource)
ddkEnv.Program("#ddk-fitter", ["fitter.cc"] + ddkLib + mpiFitter)
ddkEnv.Program("#ddk-plotter", ["plotter.cc"] + ddkLib + mpiFitter)
ddkEnv.Program("#ddk-toymc", ["toymc.cc"] + ddkLib + mpiFitter)
ddkEnv.Program("#ddk-dalitz", ["dalitz.cc"] + ddkLib + mpiFitter)

Return("ddkLib")
