Import('*')

ddkEnv = env.Clone()
ddkLib = ddkEnv.Library("ddk",Glob("src/*.cc"))
ddkEnv.Program("#ddk-fitter", ["fitter.cc"] + ddkLib + mpiFitter)
ddkEnv.Program("#ddk-plotter", ["plotter.cc"] + ddkLib + mpiFitter)
ddkEnv.Program("#ddk-toymc", ["toymc.cc"] + ddkLib + mpiFitter)

