// Class: ReadFisher
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : Fisher::Fisher
TMVA Release   : 4.0.6         [262150]
ROOT Release   : 5.26/00       [334336]
Creator        : jdalseno
Date           : Mon Sep 13 09:33:16 2010
Host           : Linux pcilc2 2.6.24-27-server #1 SMP Fri Mar 12 01:45:06 UTC 2010 i686 GNU/Linux
Dir            : /home/h1x336-03/jdalseno/belle/a1pi/fit/yield-0.1/fisher
Training events: 203660
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
# Default:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
Method: "Fisher" [Discrimination method]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 8
L0c                           L0c                           L0c                           L0c                                                             'F'    [0.117096997797,10.2917003632]
L2c                           L2c                           L2c                           L2c                                                             'F'    [1.72423999991e-12,5.45814990997]
L0n                           L0n                           L0n                           L0n                                                             'F'    [0,6.94195985794]
L2n                           L2n                           L2n                           L2n                                                             'F'    [0,4.28928995132]
CTBTO                         CTBTO                         CTBTO                         CTBTO                                                           'F'    [1.08833000922e-06,0.899980008602]
CTBz                          CTBz                          CTBz                          CTBz                                                            'F'    [4.43293993158e-06,0.943812012672]
CBz                           CBz                           CBz                           CBz                                                             'F'    [1.09836003048e-06,0.999974012375]
SumPt                         SumPt                         SumPt                         SumPt                                                           'F'    [0.221371993423,8.13580989838]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   Bool_t IsStatusClean() const { return fStatusIsClean; }

 protected:

   Bool_t fStatusIsClean;
};

#endif

class ReadFisher_svd1 : public IClassifierReader {

 public:

   // constructor
   ReadFisher_svd1( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadFisher_svd1" ),
        fNvars( 8 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "L0c", "L2c", "L0n", "L2n", "CTBTO", "CTBz", "CBz", "SumPt" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0.117096997797489;
      fVmax[0] = 10.2917003631592;
      fVmin[1] = 1.72423999991039e-12;
      fVmax[1] = 5.45814990997314;
      fVmin[2] = 0;
      fVmax[2] = 6.94195985794067;
      fVmin[3] = 0;
      fVmax[3] = 4.28928995132446;
      fVmin[4] = 1.08833000922459e-06;
      fVmax[4] = 0.899980008602142;
      fVmin[5] = 4.43293993157567e-06;
      fVmax[5] = 0.943812012672424;
      fVmin[6] = 1.09836003048258e-06;
      fVmax[6] = 0.999974012374878;
      fVmin[7] = 0.221371993422508;
      fVmax[7] = 8.13580989837646;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadFisher_svd1() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const Bool_t fIsNormalised;
   Bool_t IsNormalised() const { return fIsNormalised; }
   double fVmin[8];
   double fVmax[8];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[8];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   double              fFisher0;
   std::vector<double> fFisherCoefficients;
};

inline void ReadFisher_svd1::Initialize() 
{
   fFisher0 = 0.497577316585;
   fFisherCoefficients.push_back( 0.061411966441 );
   fFisherCoefficients.push_back( -0.424068720386 );
   fFisherCoefficients.push_back( 0.0900747744373 );
   fFisherCoefficients.push_back( -0.649796336924 );
   fFisherCoefficients.push_back( 0.171540682852 );
   fFisherCoefficients.push_back( -0.196550096784 );
   fFisherCoefficients.push_back( -0.233525670153 );
   fFisherCoefficients.push_back( 0.0457603478863 );

   // sanity check
   if (fFisherCoefficients.size() != fNvars) {
      std::cout << "Problem in class \"" << fClassName << "\"::Initialize: mismatch in number of input values"
                << fFisherCoefficients.size() << " != " << fNvars << std::endl;
      fStatusIsClean = false;
   }         
}

inline double ReadFisher_svd1::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double retval = fFisher0;
   for (size_t ivar = 0; ivar < fNvars; ivar++) {
      retval += fFisherCoefficients[ivar]*inputValues[ivar];
   }

   return retval;
}

// Clean up
inline void ReadFisher_svd1::Clear() 
{
   // clear coefficients
   fFisherCoefficients.clear(); 
}
   inline double ReadFisher_svd1::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
