// Class: ReadFisher
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : Fisher::Fisher
TMVA Release   : 4.0.6         [262150]
ROOT Release   : 5.26/00       [334336]
Creator        : jdalseno
Date           : Mon Sep 13 09:34:19 2010
Host           : Linux pcilc2 2.6.24-27-server #1 SMP Fri Mar 12 01:45:06 UTC 2010 i686 GNU/Linux
Dir            : /home/h1x336-03/jdalseno/belle/a1pi/fit/yield-0.1/fisher
Training events: 259223
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
# Default:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
Method: "Fisher" [Discrimination method]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 8
L0c                           L0c                           L0c                           L0c                                                             'F'    [0.106306999922,26.6420001984]
L2c                           L2c                           L2c                           L2c                                                             'F'    [3.89928004552e-07,10.4642000198]
L0n                           L0n                           L0n                           L0n                                                             'F'    [0,7.24314022064]
L2n                           L2n                           L2n                           L2n                                                             'F'    [0,4.03394985199]
CTBTO                         CTBTO                         CTBTO                         CTBTO                                                           'F'    [2.6474199899e-07,0.899999976158]
CTBz                          CTBz                          CTBz                          CTBz                                                            'F'    [1.63080002835e-07,0.950618982315]
CBz                           CBz                           CBz                           CBz                                                             'F'    [5.62477993071e-08,0.999966979027]
SumPt                         SumPt                         SumPt                         SumPt                                                           'F'    [0.228419005871,14.7494001389]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   Bool_t IsStatusClean() const { return fStatusIsClean; }

 protected:

   Bool_t fStatusIsClean;
};

#endif

class ReadFisher_svd2 : public IClassifierReader {

 public:

   // constructor
   ReadFisher_svd2( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadFisher_svd2" ),
        fNvars( 8 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "L0c", "L2c", "L0n", "L2n", "CTBTO", "CTBz", "CBz", "SumPt" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0.106306999921799;
      fVmax[0] = 26.6420001983643;
      fVmin[1] = 3.89928004551621e-07;
      fVmax[1] = 10.4642000198364;
      fVmin[2] = 0;
      fVmax[2] = 7.24314022064209;
      fVmin[3] = 0;
      fVmax[3] = 4.03394985198975;
      fVmin[4] = 2.64741998989848e-07;
      fVmax[4] = 0.899999976158142;
      fVmin[5] = 1.63080002835159e-07;
      fVmax[5] = 0.950618982315063;
      fVmin[6] = 5.62477993071298e-08;
      fVmax[6] = 0.999966979026794;
      fVmin[7] = 0.228419005870819;
      fVmax[7] = 14.749400138855;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadFisher_svd2() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const Bool_t fIsNormalised;
   Bool_t IsNormalised() const { return fIsNormalised; }
   double fVmin[8];
   double fVmax[8];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[8];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   double              fFisher0;
   std::vector<double> fFisherCoefficients;
};

inline void ReadFisher_svd2::Initialize() 
{
   fFisher0 = 0.798949397671;
   fFisherCoefficients.push_back( 0.0828140973669 );
   fFisherCoefficients.push_back( -0.456723776696 );
   fFisherCoefficients.push_back( 0.1790813666 );
   fFisherCoefficients.push_back( -0.968701810889 );
   fFisherCoefficients.push_back( 0.0446648140775 );
   fFisherCoefficients.push_back( -0.0359048713247 );
   fFisherCoefficients.push_back( -0.366502423515 );
   fFisherCoefficients.push_back( 0.0159130211328 );

   // sanity check
   if (fFisherCoefficients.size() != fNvars) {
      std::cout << "Problem in class \"" << fClassName << "\"::Initialize: mismatch in number of input values"
                << fFisherCoefficients.size() << " != " << fNvars << std::endl;
      fStatusIsClean = false;
   }         
}

inline double ReadFisher_svd2::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double retval = fFisher0;
   for (size_t ivar = 0; ivar < fNvars; ivar++) {
      retval += fFisherCoefficients[ivar]*inputValues[ivar];
   }

   return retval;
}

// Clean up
inline void ReadFisher_svd2::Clear() 
{
   // clear coefficients
   fFisherCoefficients.clear(); 
}
   inline double ReadFisher_svd2::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
